import React from "react";

const page = () => {
  const terms = `
These policies are published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, and are an ‘electronic record’ as contemplated under section 2(t) of the Information Technology Act, 2000 and the Rules thereunder. These Terms being an electronic record are generated by a computer system and do not require any physical or digital signatures.

ACCESS TO THE APP

Favobliss App is yet to be completed. Work in progress.

Accessing, browsing or otherwise using the App will be construed as Your unequivocal and irrevocable acceptance and acknowledgement to the terms and conditions contained under Terms of Use and binding policies hereof. By using the App, You declare to have carefully read, understood and agree to be bound by these Terms of Use. Favobliss.com may at its sole discretion allow or disallow access to App and reserves the right to change any of the terms and conditions contained herein at any point in time. It is Your responsibility to periodically review these Terms of Use any update and changes and Your continued use of the App will be considered as Your acceptance to such updates and changes.

ELIGIBILITY

You should have completed 18 years of age and be competent to enter into a contract under Indian contract law. If You are under 18 years of age who is intending to avail the services of the App should do so through Your legal guardian in accordance with applicable law.

If You are using the App on behalf of any corporation, company, institution, association or other entity, the person should be authorized by such corporation, company, institution, association or other entity to use and access the App.

Favobliss.com reserves the right to refuse access to use the services offered at the App to new users or to terminate access granted to existing users at any time without according any reasons for doing so.

COMPLIANCE REQUIREMENTS

Every User of the App shall comply with all the applicable laws, including but not limited to the Foreign Exchange Management Act, 1999, notifications issued there under the Exchange Control Manual issued by the Reserve Bank of India, Customs Act, 1962, Information Technology Act, 2000, Prevention of Money Laundering Act, 2002, Foreign Contribution Regulation Act, 1976, Income Tax Act, 1961, Export Import Policy of the Government of India and shall include any amendments, notifications and Rules thereof under the aforesaid enactments applicable for using the App or buying/ selling any product or service through the App.

USER ACCOUNT

You may be required to register and set up an account (“Account”) for using the App by entering an email address and password or by using any permitted social media the App account to sign in ("Account Information"). Favobliss.com as its sole discretion may ask for the verification of Your Account Information provided by You and hence, it is advisable to provide a valid information e.g. like email address or mobile number etc. while creating an Account. The App will set-up an account and email the details of the Account at the email address provided. You can also create and update an Account through Customer Support.

You can create one Account only and it is not permitted to transfer or interchange such Account to any other person. The list of information required to be provided by You, the manner of usage, protection and confidentiality of Your information and Account information are more specifically dealt under the App’s Privacy Policy and You are requested to read the Privacy Policy in detail before sharing Your information or creating an Account.

PAYMENT POLICY

Payment is an integral part of an online shopping experience. All payments shall be collected through secured payment options.

We accept all prepaid payment options such as all the major Credit Cards, Debit Cards, Net-Banking etc. Favobliss.com may also offers industry-leading solution for Cash on Delivery.

All payments for purchases made by You on the App shall only be in Indian Rupees. In case of a prepaid transaction, after payment for the order has been successfully received by Favobliss.com, You will be sent a notification by email or SMS at the email address or mobile number provided to Favobliss.com confirming receipt of payment. There may be limits to the amount of Cash on Delivery payments based on pin codes or the State in India where delivery is to be made. Favobliss.com reserves the right to withdraw or block or limit Your purchases using Cash on Delivery basis transaction history.

Credit and Debit Card

Favobliss.com accepts all Visa, Master Card, Maestro, American Express and Diners cards. You will be redirected to Your issuing bank's site, where You will have to follow the instruction to complete the payment.

Net Banking

You can make payment for an order by using Your Net Banking account. The App accepts payments for Your orders to sellers through various banks. You will be redirected to Your bank's site where You will be able to make payment after entering in Your login id and password that is known only to You.

EMI Payments

EMI is one of the payment methods available on Favobliss.com for Your convenience which allows You to pay for Your orders easily. The equated monthly installments payment method is only available for customers using certain credit cards as per the relevant terms and conditions being in force. Applicable charges/fees/costs, if any, levied by the Bank for facilitating EMI, shall be directly and solely borne by the Customer. Favobliss.com does not charge any processing or convenience fee for the said purpose. Any dispute in this regard shall be directly dealt by the Customer with the Bank and Favobliss.com shall not be held liable in any case, whatsoever.

Cash on Delivery

Cash on Delivery is one of the payment methods for making purchases on Favobliss.com where You don't have to make any advance payment.

Cash on Delivery is available as a payment method for all eligible products on Favobliss.com. Eligible products will be indicated by the message [‘Eligible for Cash on Delivery’] on the [‘product order page’] for delivery in certain pin codes.

Issues with Payments - Pending Payments:

Payments can sometimes fail or remain in the pending stage. Some of the reasons could be:

1. Incorrect debit or credit card details are entered.
2. Card may be blocked or card details are no longer valid or need to be updated.
3. The page is accidentally closed or refreshed or backspace is pressed while the transaction is being processed by Your bank.
4. The connection between Favobliss.com and Your bank or issuer failed due to some technical reasons and the transaction could not be completed.
5. Card or bank or issuer is not recognised by Favobliss.com.
6. Incorrect login or password details are entered.
7. Payment amount exceeds the limit mutually agreed to between You and Your bank or issuer.

If You face any of the above payment issues, try placing the order again in a short while or contact Your bank or issuer for technical assistance. Favobliss.com is not liable for any loss or inconvenience caused to You when making payment or for any wrongful debits to Your cards or net banking accounts.

Issuing Bank Terms and Conditions

Users understand and acknowledge that all payments made by the Users using valid credit card/ Debit card/ Cash Card/ and other payment instruments or mechanism including net banking facility will be processed using a payment gateway or appropriate payment system infrastructure and the same is governed by a separate set of terms and conditions agreed between the User and the respective Issuing Bank and payment instrument issuing company.

Requirements of Permanent Account Number (PAN)

For all the purchase of an amount equal to or exceeding INR 2,00,000 (INR two lakhs only), You will be required to upload a copy of Your PAN card, within such time as may be prescribed from the date of purchase, failing which, the purchase made by You will be automatically cancelled. The order shall also stand cancelled if there is a discrepancy between Your name in Account with Favobliss.com the name printed on the PAN card.

The requirement to provide a copy of PAN card is one time activity and You don’t need to submit it again.

DELIVERY POLICY

Shipping Address

 

Your shipping address and pin code will be verified with the database of Favobliss.com

before You proceed to pay for Your purchase. In the event Your order is not serviceable by our logistics service providers or the area is not covered, we will request You to provide us with an alternate shipping address. You can make purchases on the App from anywhere in the world but at the same time You must ensure the payment and shipping address is within India.

 

When You submit an alternative address for delivery, You are responsible for accepting and collecting the package from such alternative address. Confirmation from the logistics service provider of successful delivery to the alternative shipping address is deemed as acceptance of delivery by You and Favobliss.com will have no liability in this regard.

 

 Delivery to Partner Store (subject to the availability of function and the facilities by seller)

 

 Instead of delivering the order to Your shipping address, You can choose to have Your product delivered to a partner store so You can pick-up the package from the partner store at Your convenience. On Your collecting the package You will receive a notification by email or SMS at the email address or mobile number provided to Favobliss.com confirming delivery of the product. Click here to get a list of our partner stores. If You do not collect the product from the partner store within allowed time, the product will be returned to the seller and Your order will be cancelled. No refund due to non-deliverability will be applicable to orders placed with Cash on Delivery options.

 

 Delivery by Favobliss.com or Seller

 

The delivery of the ordered products from the seller to You will be made by logistics service providers assigned by Favobliss.com or Sellers. However, large and bulky products such as televisions, refrigerators, air-conditioners, etc. may be delivered to You directly by the seller. Deliveries cannot be rescheduled after the order has been placed. 



The logistics service provider assigned by Favobliss.com will make a maximum of three [3] attempts to deliver Your order. In case You are not reachable, available or do not accept delivery of products in these attempts Favobliss.com reserves the right to cancel the order at its discretion. You may be informed of such cancellation by email or SMS at the email address or mobile number provided to Favobliss.com. The cancelled order is returned to seller. You agree not to hold Favobliss.com liable for any cancellation.

 

If You wish to request the App to resend the product, You can do so by placing a new order for the product on the terms set out on the [‘product order page’] when You place the new order. Your order will be accepted subject to availability of the product.

 

In case there is any dispute regarding the shipment of the product or serviceability for the area not covered by the logistics service providers, Favobliss.com will not be responsible for the non-delivery of the product.

 

Title and risk of loss for all products ordered by You shall pass on to You upon delivery of the products at the shipping address provided by You.

 

Multiple Product Orders

 

In case You order multiple products in one transaction, Favobliss.com would endeavour to ship all products together. However, this may not always be possible due to some product characteristics or logistics issues or the location of seller and You may receive the products separately and at different times. If You purchase multiple products in a single transaction, then all the products would be dispatched to a single shipping address given by You. If You wish to ship products to different addresses, then You should book the orders separately based on the shipping addresses.

 

Missing Items

 

In the event, the product package received by You is missing one or more products or accessories or does not include the freebie or the order is partly delivered, You should inform Favobliss.com through the Customer Care Team within 5 days of delivery date of the package. Missing products claims will not be accepted after 5 days from delivery date.

 

When a package delivered is missing one or more products or accessories, You are requested to return the original package delivered to the seller in accordance with the Return Policy.

 

In the event of dispute, Favobliss.com will coordinate with You and the seller to reach an amicable solution. Favobliss.com is only a facilitating link between You and the seller and will not be liable in any manner.



Refusal of Delivery

 

Before accepting delivery of any product, kindly ensure that the product's packaging is not damaged or tampered. If You observe that the package is damaged or tampered, You are requested to refuse to accept delivery and inform Favobliss.com within 5 days of delivery date.

 

You are requested to fill the delivery sheet / acknowledgement used by the logistics service providers and note down the condition of the delivered package. Damaged or tampered products claims will not be accepted beyond the returns policy

 

In the event of dispute, Favobliss.com will coordinate with You and the seller to reach an amicable solution. Favobliss.com is only a facilitating link between You and the seller and will not be liable in any manner.

 

Delivery Time

 

An estimated delivery time of each product will be displayed on the [‘product order page’]. On placing Your order, You will receive an email or SMS at the email address or mobile number provided to Favobliss.com containing a summary of the order and also the estimated delivery time to Your location. The seller may take additional time to pack and dispatch certain products and this time will be indicated by the message on the [‘product order page’]. This period of time is to be added to the shipping speed You choose.

 

Delivery timeframes are just estimates and are not guaranteed delivery timeframes and should not be relied upon as such. Deliveries to certain locations may take longer than expected due to accessibility of the location and serviceability by the logistics service provider.



 

About Delayed Delivery



 

Sometimes, delivery may take longer due to:

 

1. Bad weather.

 

2. Transportation delays.

 

3. Natural calamities.

 

4. Political disruptions.

 

5. Logistics service provider related 



6. Regional or national holidays which are considered as delivery holidays.

 

7. Other unforeseen circumstances or events beyond the control of Favobliss.com or logistics service provider.

 

 

If the estimated delivery date has passed and You still have not received Your order, please contact us and we will take steps to track Your package. In such cases, we may also try to proactively contact You. Please check Your emails and SMS regularly for such updates.

 

 

Favobliss.com will not compensate for any mental agony or inconvenience or loss caused due to delay in delivery for any reason. You may be informed by email or SMS at the email address or mobile number provided to Favobliss.com if any product in the order is unavailable or is delayed or lost in transit.

 

 

Shipping Charges

 

You may be required to pay Shipping Charges in addition to the order value amount. The shipping charges, if any, will appear at the time of checkout. All delivery charges are inclusive of service tax unless stated otherwise. Shipping Charges may vary for different pin code because of the increase in shipping cost or seller’s is located in a different area. Delivery charges will vary according to pin codes as well as type of product.

 

 

Open delivery

 

Favobliss.com reserves the right to provide Open delivery or not. Open delivery service which is provided by Favobliss.com with some Specifics logistics service providers. Open delivery depends upon our logistics service provider’s service dependencies. You can’t open parcel if logistics service provider doesn’t allow and in such event, You have a right to accept the parcel after paying the amount and thereafter You can use our hassle-free return policy.

 

Please refer to the Return and Refund Policies, if You wish to return the delivered product to Favobliss.com.

 

RETURN POLICY



Reasons for Return

 

Return Policy makes it possible for You to return a product if You receive a damaged or defective product or if the product is significantly different from what was purchased or when the package delivered is missing one or more products or accessories. Return Policy here should be read in conjunction with the any specific terms and conditions applicable to a product which can be found on product descriptions page for returning a product.

 

Conditions for Return

 

In order to return any product sold through the App, You are required to comply with the below mentioned conditions, viz.:

 

 

 

1. The return has to be in compliance with the Return Policy associated with the product category.

 

2. Favobliss.com should be notified of the receipt of a damaged or defective product or if the product is significantly different from what was purchased, within period mentioned in the returns policy.

 

3. Products should be returned unused, in their original packaging along with the original price tags, labels, packing, barcodes, user manual, warranty card and invoices, accessories, freebies and original boxes defined as essentials. If any product is returned without the essentials, the product shall not be accepted for return and shall be sent back to You.

 

4. The return packages should be strongly and adequately packaged so that there is no damage of products during transit.

 

5. The returned products are subject to verification and quality checks by the sellers selling on Favobliss.com in order to determine the legitimacy of the complaint or return.

 

6. If You have chosen the partner store option for delivery of the order and wish to return the product, You should return the product to the same store from where You collected the order or to other store that the partner might allow from time to time. You should return the product in original and unused condition along with all original price tags, labels, packing, barcodes, user manuals, warranty card and invoices, accessories, freebies and boxes received. Store reserves the right to accept the product and after quality check.

 

7. You should fill the Return Form provided by Favobliss.com with the originally delivered package or make available to You over email or account and include it in the returned package. Return requests are not processed if the Return Form is incomplete or absent in the returned package received. The reason for return should be stated in the Return form. You should additionally fill out the delivery sheet used by the logistics service providers and note down any damaged or tampered condition of the delivered package.

 

8. The return has to be in compliance with the return policy of the seller or the manufacturer of the product where applicable.

 

 

Non-returnable Products

 

 

All products cannot be returned. Some of the products that cannot be returned are:

 

 

1. Innerwear, lingerie, socks, clothing freebies and swimsuits.

 

2. Perfumes, personal and beauty care or other consumables.

 

3. Products that have been used or installed.

 

4. Products damaged due to misuse of product or products having incidental damages due to malfunctioning.

 

5. A product with defects not covered under manufacturer’s warranty.

 

6. Products with tampered or missing serial numbers.

 

7. Personalised or engraved products or resized products.  

 

8. Product sold in sets or combination cannot be returned individually.

 

9. Any other product depending upon the Return Policy in force.

 

10. Software, Video Games (discs), printer cartridges.

 

 

If You are unable to inform Favobliss.com of the receipt of a damaged or defective product or the product is not as per specifications of Your order or the package delivered is missing one or more products or accessories as per the returns policy and procedure, Favobliss.com or Seller shall not be obliged to accept the returned product or be liable in this regard. In the event, such product is sent to Seller, the product will be returned to the Customer and the same needs to be accepted from Seller or assigned logistics service provider. Favobliss.com or seller will not be responsible if the product is not accepted and no refund will be issued.



 

Damaged, Defective or Other Non-conforming Products

 

 

Returns of damaged, defective or other products eligible for return are accepted as under:

 

 

i.  In the event You receive a damaged or defective product or a product that does not comply with the specifications as per Your original or the product is delivered after the expected delivery period or the package delivered is missing one or more products or accessories and eligible for return as described by Return Policy, You are required to get in touch with the Customer Care Team through any of the below mentioned channels or submit a return request online (if such facility is available) as per the Returns Policy.

 

ii. Upon receiving Your return request, Favobliss.com shall verify the authenticity and the nature of the request and if the request is genuine, Favobliss.com will inform the seller of the return request and will ask the seller for a refund to be processed upon the receipt and quality check of the returned product. It will take a minimum of [4-6] business days to process Your request for return of products.

 

iii. Favobliss.com or Seller may arrange for pick-up of the product through an assigned logistics service provider. You will receive an email or SMS notification at Your email address or mobile number provided to Favobliss.com. In the event Favobliss.com is unable to arrange pick-up, Favobliss.com will notify You regarding the same and You will be required to send the product to the seller at the provided address using a reputed courier service in Your area.

 

iv. For return of large and bulky products such as televisions, refrigerators, air-conditioners, etc. the seller will arrange for pickup.

 

v. If Your pin code is not serviceable, Favobliss.com may ask You to ship the product to the seller using a relevant and available logistics service provider or Indian Postal services. Customers are required to submit the shipping information of the self-ship by contact Customer Service. In the event the details are not provided and the shipment arrives without returns form or invoice, the refund may be delayed.

 

vi. Upon receipt of the returned product by the seller and successful completion of the quality check, You will receive an email or SMS confirmation at the email address or mobile number provided to Favobliss.com. 

 

vii. You will be refunded the product cost along with taxes and shipping charges, if any. Courier freight charges You paid to courier or shipping service for returning the product to seller will be reimbursed as per method agreed with You.

 

 

 

You expressly acknowledge that the seller is solely responsible for the damaged or defective product or a product that does not meet the specifications of Your original order or delayed delivery of the order or delivery of the package with one or more products or accessories missing and for any claims that You may have in relation to such products and Favobliss.com shall not in any manner be held liable for the same. In the event of dispute, Favobliss.com will coordinate with You and the seller to reach an amicable solution. Favobliss.com is only a facilitating link and an Intermediary as per definition under Information Technology Act, 2000 and rules framed there under, between You and the seller and Favobliss.com will not be liable in any manner.

 

 

 

Dead on Arrival Products

 

 In the event, You receive an electronic or technological product that is has manufacturing defect or is dead on arrival, You should inform Favobliss.com the period defined in the returns policy and place a request for return by following the procedure defined in the Returns Policy. You may be asked to obtain a manufacturer defect or Dead on Arrival certificate from the manufacturer or an authorised service centre of the manufacturer. This certificate will have to be produced to Favobliss.com for processing Your return request and sent to seller along with the product Favobliss.com may engage with a third party at its own discretion to help Customers obtain this certificate and cannot be held responsible for any delay or mishandling of products. If the products are found to be working or the defect is caused to any mishandling, product will be returned back to You. Customers are required to accept the return

 

 

 

In case a dead-on arrival certificate cannot be issued by an authorised service centre of the manufacturer, You will be required to get the product serviced or repaired as per warranty provided by the manufacturer and Favobliss.com will not be liable in any manner. In the event the certificate provided as dead on arrival certificate is disputed by the manufacturer or deemed as invalid, the product will be returned to You and Favobliss.com will not be liable in any manner.

 

 

 

Period for Return

 

 

 

Please refer “Know More” section of the product information page for the Period of Return i.e. period within which a product delivered can be returned by the Buyer subject to the other terms and conditions of the Return Policy contained hereunder.

 

 

 

Cancellation of Return Request

 

 

 

A request for return once made can be cancelled by contacting Customer Service. In case the Logistics Service provider arrives to receive the shipment and You want to cancel the request, You may choose to inform the logistics service provider that You do not wish to return the product. You will receive an email or SMS notification at the email address or mobile number provided to Favobliss.com cancelling Your return request.

 

 

 

Refusal of Return Request

 

 

 

Favobliss.com reserves the right to refuse or cancel any return request.  If the request for returns is not allowed by the Returns Policy, You will not be refunded the payment made or any costs and will not be able to raise a second request for return for the same product. You agree not to dispute the decision made by Favobliss.com and accept Favobliss.com’s decision regarding the refusal or cancellation and further agree not hold Favobliss.com liable for any refusal or cancellation.

 

 

 

Frivolous Complaints

 

 

 

In the event of frivolous or baseless complaints or requests regarding the quality or content of the products, Favobliss.com reserves the right to take necessary legal actions against You and You will be solely liable for all costs incurred by Favobliss.com in this regard.

 

 

 

Return Shipping Process

 

 

 

Self-send Process

 

 

 

In case of return of products initiated and subsequent courier of the product by You, if it is found that the returned product was not delivered to the seller or any other designated location specified or the package was empty, the onus shall be on You to prove through submission of proof of delivery from the concerned courier service provider to establish Your claim of return. Self-courier of returns should be initiated within the periods specified in the Favobliss.com’s Returns Policy. Favobliss.com is not liable to process the return request until satisfactory proof of delivery is provided to Favobliss.com.

 

 

 

In case of damage claims, Favobliss.com may ask for pictures of the damaged product before it is approved or allowed for return.

 

 

 

For return shipping managed by Favobliss.com, You will need to hand over the product to the assigned logistics service provider at the time of pick-up. In the event the logistics service provider makes attempts to pick-up the product and You are unavailable or not ready to handover the product, Favobliss.com or logistics service provider will not be held responsible for the delay in pick-up or processing of the quality check by the seller and hence the refund. A maximum of 2 attempts will be made by the logistics service provider to pick-up the product to be returned. Favobliss.com will not be liable for the products returned by mistake.

 

 

 

In the event where a product not belonging to the seller selling on Favobliss.com is returned by mistake, Favobliss.com is not accountable for such misplacement and is not responsible for its delivery back to You or any costs incurred by You or any refund.

 

 

 

Discrepancy Between Information Provided by You and Our Logistics Service Provider

 

 

 

In case of any discrepancy in the status of pick-up of a product arranged by Favobliss.com, (where You claim the product has been returned, while our system suggests otherwise) refund will be initiated only if You successfully furnish the courier slip given by the Favobliss.com assigned logistics service provider at the time of the pick-up.

 

 

 

In case where a seller or designated return location claims that the product received from You is different or the return of the product is not in compliance with the Returns Policy, the product will be dispatched back to Your shipping address and You are required to receive and accept the package. In the event of dispute, Favobliss.com will coordinate with You and the seller to reach an amicable solution. Favobliss.com is only a facilitating link between You and the seller and will not be liable in any manner.

 

 

 

ORDER CANCELLATION POLICY

 

 

 

Cancellation of an order can be done either by Favobliss.com or by You as under:

 

 

 

Cancellation by Favobliss.com

 

 

 

Favobliss.com has the discretion to cancel an order. Some of the reasons for cancellation are as under (not being exhaustive list of reasons):

 

                I.       Your failure to comply with any of these terms.

 

              II.       Product is unavailable with the seller.

 

            III.       Technical errors or issues.

 

           IV.       Any reason identified by Favobliss.com's credit and fraud avoidance team.

 

             V.       Invalid address or wrong address is given in order details.

 

           VI.       Malpractices used to place the order.

 

         VII.       Bulk order is placed for the likely commercial resale.

 

       VIII.       Multiple orders are placed for same product at the same address.

 

           IX.       Order is undelivered after three (3) attempts.

 

             X.       EMI offer is rejected by the bank.

 

           XI.       Failure to collect the order from partner store within stipulated time.

 

         XII.     Pricing or specifications on any product as is shown on the App due to typographical error or incorrect information inadvertently provided by the seller or some technical glitch, resulting into incorrect pricing or specifications.

 

 

 

Notwithstanding anything contained hereunder, Favobliss.com reserves the right, at its sole discretion, to refuse or cancel any order for any reason whatsoever without any further liability. On such cancellation, You will be sent a notification email or SMS at the email address or mobile number provided to Favobliss.com.

 

 

 

You agree to release and indemnify Favobliss.com, its officers and representatives from any cost, damage, liability or any of the actions in case of cancellation of Your Order by Favobliss.com or seller.

 

 

 

Cancellation by You

 

 

 

You may cancel an order for any reason, although cancellation by You must be done before the product has been shipped for delivery to You. No cancellation is permitted subsequently.

 

 

 

You can cancel an order, or part of an order where multiple products have been ordered. This can be done either by calling or emailing Customer Care Team or in Your account on the App through ‘my account’. You should state the reason for such cancellation. Favobliss.com will process the request for cancellation as per the policy in force.

 

 

 

If an order has been successfully cancelled, You will be sent a confirmation email or SMS at the email address or mobile number provided to Favobliss.com.

 

 

 

Favobliss.com reserves the right to accept or reject requests for order cancellations for any reason whatsoever. You agree not to hold Favobliss.com liable for any rejection of order cancellations.

 

 

 

You will receive a refund for Your cancelled orders that have been accepted in accordance with the Refund Policy.

 

 

 

REFUND POLICY

 

 

 

Refunds

 

 

 

Refunds are provided for cancellation / return of products, subject to the eligible cancellation/ return as per Return Policy or these terms and conditions, initiated in accordance with the Return or Cancellation Policy.

 

 

 

Refund is made for the full amount of the order or part order successfully cancelled that was paid by You for the delivery of the order.

 

 

 

For return requests, the refund of payment is made after the returned product has been received by the seller and has passed the quality checks. The entire product cost along with any taxes and shipping charges if any will be refunded to You.

 

 

 

If any refund is received by You pending the quality checks, You will hold such amounts in trust on behalf of Favobliss.com until conclusion of such quality checks unless claimed by Favobliss.com any time before that. If You are in receipt of any wrongful refunded or payment, You will transfer such amount back to Favobliss.com within 3 days of You receiving such amount.

 

 

 

No refund due to non-deliverability will be applicable to orders placed with Cash on Delivery options. Refund of Cash on Delivery orders returned by You may subject to levy of a charge which will be deducted from Your refund amount.

 

 

 

Time Period for Refunds

 

 

Refunds are normally processed within 1-6 working days after the completion of quality checks of product returned and further depends on various banking and payment channels.

 

Interest charged by the bank providing the EMI Scheme till the time the request for return or cancellation is raised will not be refunded. `.trim();

  const formatTerms = (raw: string) => {
    const headings = new Set([
      "ACCESS TO THE APP",
      "ELIGIBILITY",
      "COMPLIANCE REQUIREMENTS",
      "USER ACCOUNT",
      "PAYMENT POLICY",
      "DELIVERY POLICY",
      "RETURN POLICY",
      "ORDER CANCELLATION POLICY",
      "REFUND POLICY",
    ]);

    return raw.split("\n").map((line, idx) => {
      const text = line.trim();

      // blank line spacing
      if (!text) return <div key={idx} className="h-3" />;

      // numbered list item
      if (/^\d+\.\s+/.test(text)) {
        return (
          <p key={idx} className="text-sm md:text-base leading-7 text-gray-700">
            {text}
          </p>
        );
      }

      // main headings
      if (headings.has(text.toUpperCase())) {
        return (
          <h2
            key={idx}
            className="mt-6 mb-2 text-lg md:text-xl font-semibold text-gray-900"
          >
            {text}
          </h2>
        );
      }

      // sub headings (simple heuristic)
      if (text.length <= 40 && text === text.toUpperCase()) {
        return (
          <h3 key={idx} className="mt-4 mb-1 text-base font-semibold text-gray-900">
            {text}
          </h3>
        );
      }

      // normal paragraph
      return (
        <p key={idx} className="text-sm md:text-base leading-7 text-gray-700">
          {text}
        </p>
      );
    });
  };

  return (
    <div className="w-full flex flex-col text-center items-center justify-center mb-8">
      <h1 className="text-3xl font-bold mt-10">Favobliss Terms & Conditions</h1>

      {/* Added: content container */}
      <div className="w-full max-w-5xl mt-6 px-4">
        <div className="text-left bg-white rounded-xl border border-gray-200 shadow-sm">
         

          <div className="px-5 md:px-8 py-6 max-h-[75vh] overflow-y-auto">
            {formatTerms(terms)}
          </div>
        </div>
      </div>
    </div>
  );
};

export default page;
